In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from sklearn.impute import SimpleImputer
from sklearn import linear_model 
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn import preprocessing
from sklearn.model_selection import GridSearchCV
from matplotlib import pyplot as plt
from sklearn.metrics import make_scorer
from sklearn.metrics import accuracy_score
from sklearn import tree
from sklearn.preprocessing import scale, StandardScaler, OneHotEncoder
import sklearn
from sklearn.decomposition import PCA
from sklearn.impute import KNNImputer

In [3]:
df = pd.read_excel("esg_project21.xlsx")
df.head(5)

,esg_score21,esg_class21,environ_score21,environ_class21,social_score21,social_class21,govern_score21,govern_class21,turnover21,country,...,esg_exe_remuneration,esg_respect_humanr,esg_human_rights,esg_respect_freedom,esg_non_discrimination,esg_physical_risk,esg_energy_transition,esg_carbon_emission1,esg_carbon_emission2,esg_carbon_emission1_2
0,20,Weak performance,0,Weak performance,17,Weak performance,36,Limited performance,490490,USA,...,28,22,25,22,27,0,0,n.d.,n.d.,5537
1,26,Weak performance,18,Weak performance,22,Weak performance,40,Limited performance,2122245,USA,...,43,31,28,23,33,43,13,2300,40984,43284
2,31,Limited performance,20,Weak performance,29,Weak performance,48,Limited performance,102731,USA,...,46,46,34,24,47,39,10,748,7379,8128
3,24,Weak performance,9,Weak performance,21,Weak performance,38,Limited performance,54522,USA,...,29,36,27,23,35,1,5,6222,18748,24970
4,24,Weak performance,15,Weak performance,19,Weak performance,39,Limited performance,83,USA,...,38,32,25,18,30,1,11,326,1363,1689

### Reemplazo NaNs, eliminación y tratmiento de las columnas (basicos)

In [5]:
def preproces(df):
    
    # Limpieza de nombres de columnas
    df.columns = df.columns.str.strip()
    
    # Reemplazo los n.d. y valores vacíos por NaN 
    df.replace({"n.d.": np.nan, "": np.nan, 'n.s.': np.nan}, inplace=True)
    
    # Calculo el porcentaje de NaN por columna
    nan_per = df.isna().mean() * 100
    
    # Filtro las columnas con mas del 80% de NaN
    columnas_mas_80 = nan_per[nan_per > 80].index
    
    # Elimino las columnas con más del 80% de NaN
    df.drop(columns=columnas_mas_80, inplace=True)
    
    return df

In [6]:
# Supongamos que 'df' es tu DataFrame original y 'preproces' es tu función
clening_basic_df = preproces(df)

# Guardar el DataFrame en un archivo CSV
clening_basic_df.to_csv('clening_basic_data.csv', index=False)

print("Archivo guardado como 'clening_basic_data.csv'")

NameError: name 'preproces' is not defined